# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: 'BABS project report' # Website name
baseurl: '' # Website URL
copyright: '' # Footer text, e.g. '© {year} Me'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
disableAliases: true
timeout: 600000
sectionPagesMenu: "main" # auto list in `main` navbar

ignoreFiles: 
  - \.bibtex$
  - \.R$
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rprofile$
  - \.Rproj.user$
  - \.Rproj$
  - _rslurm_*
  - knitr_cache
  - renv
  - renv.lock
  - scratch

# https://gohugo.io/getting-started/configuration-markup/
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true # `true` to include html from markdown (eg figures!)
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 5

permalinks:
  docs: '/:year/:month/:day/:slug/'
  books: '/:year/:month/:day/:slug/'

outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart

taxonomies:
  tag: tags
  category: categories
  author: authors

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70

publications:
  citation_style: apa
