# SITE SETUP
# guide: https://wowchemy.com/docs/getting-started/
# documentation: https://wowchemy.com/docs/
# this file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# appearance

theme: crick
day_night: true
font: ubuntu
font_size: m
favicon: icons/CRICK_favicon.png
# logo: logos/CRICK_Brandmark_01_CMYK.svg

# search engine optimisation

site_type:
local_business_type: ''
org_name: ''
description: ''
twitter: ''

# site header

main_menu:
  # Display the navigation bar?
  enable: true
  # Align menu links: left (l), center (c), or right (r)
  align: l
  # Display your site title or `assets/media/logo*` image in the nav bar?
  show_logo: true
  # Show a language chooser (if you have translated your site content)?
  show_translations: false
  # If `show_translations` is enabled, do you wish to display the current language name?
  show_language: false
  # Let the user override the default light/dark mode of your theme?
  show_day_night: true
  # Let the user search from the navbar?
  show_search: true
  # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
  highlight_active_link: true

# localization

date_format: '2 Jan, 2006'
time_format: '3:04 PM'
address_format: en-gb

# site features

## syntax highlighting with HighlightJS
## https://wowchemy.com/docs/content/writing-markdown-latex/#code-highlighting
highlight: true
highlight_style: monokai-sublime
highlight_languages:
  - bash
  - python
  - r

## other
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    book: false
    docs: false
show_related:
  book: false
  docs: false
sharing_image: ''
reading_time: true
section_pager: false
docs_section_pager: false
book_section_pager: false
sharing: false
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
breadcrumb:
  page_types:
    book: false
comments:
  provider: ''
  commentable:
    book: false
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
profile: false # author tag in footer
textcite:
  sep: "; "
  last: ' and '
