#! /bin/env bash

profile=${1:-basic}
root_path=${2:-_assets/books}

echo "profile=$profile"
echo "root_path=$root_path"

for qmd_file in $(yq eval '.book.["chapters","appendices"]' _quarto-$profile.yaml | sed 's/- //'); do
	output_path=$(dirname $qmd_file)

	mkdir --parents $output_path
	cp $root_path/$qmd_file .

	echo "qmd_file=$qmd_file"
done
