metadata-files:
  - _configs/default/execute.yaml
  - _configs/default/format.yaml
  - _configs/default/metadata.yaml
  - _configs/default/project.yaml
  - _configs/default/website.yaml
  - _configs/project/metadata.yaml
  - _configs/project/website.yaml
