project:
  type: book

book:
  title: "{{< meta babs.scititle >}}"

  sidebar:
    title: "{{< meta babs.limsid >}}"

website:
  title: project/website/title
  description: project/website/description
  # repo-url: http://github.com/BABS-STP/cb001

  sidebar:
    title: project/website/sidebar/title
