book:
  title: Cell Ranger ARC

  chapters:
      - index.qmd
      - cell-ranger/arc/write-sample-csvs/index.qmd
      - cell-ranger/arc/count/index.qmd

  appendices:
    - references/index.qmd
    - environments/index.qmd

format:
  html:
    bibliography:
      - _assets/bibliography/cell-ranger-arc.bib

