---
# An instance of the Hero widget.
# Documentation: https://wowchemy.com/docs/page-builder/
widget: blank

# Activate this widget? true/false
active: true

# This file represents a page section.
headless: true

# Order that this section appears on the page.
weight: 21

title: Background project information
subtitle:

hero_media:

design:
  columns: '1'
  spacing:
    padding: ["20px", "0px", "0px", "0px"]
---

```{r setup, echo=FALSE, cache=FALSE, warning=FALSE, message=FALSE}
options(warn=-1)

library(knitr)
library(purrr)
library(stringr)
library(datarepository)
library(docxtractr)

opts_chunk$set(echo=FALSE, cache=FALSE, results='asis', warning=FALSE, message=FALSE)
```

```{r get_docx}
system.file('docs/proposal.docx', package='datarepository') %>%
  when(file.exists(.)~read_docx(.),
       TRUE~NULL) -> proposal_docx

safely_docx_extract_tbl <- safely(docx_extract_tbl, otherwise="Error extracting table element from proposal.docx, you'll have to go in manually.")
safely_pluck <- function(x, i) pluck(x, i, .default="Error extracting element from within table, you'll have to go in manually.")
```

## Project summary

```{r get_project_summary, eval=class(proposal_docx)=='docx'}
proposal_docx %>%
  safely_docx_extract_tbl(tbl_number=3, header=FALSE, preserve=TRUE) %>% pluck('result') %>%
  unlist() %>%
  safely_pluck(1) %>%
  str_remove('Project Summary\n*') %>%
  str_replace_all('  +', ' ') %>%
  str_remove('\\s+$') %>%
  cat()
```

## Experimental approach

```{r get_experimental_approach, eval=class(proposal_docx)=='docx'}
proposal_docx %>%
  safely_docx_extract_tbl(tbl_number=3, header=FALSE, preserve=TRUE) %>% pluck('result') %>%
  unlist() %>%
  safely_pluck(6) %>%
  str_remove('Experimental Approach: *\nPlease include details such as the number of biological and / or technical replicates:\n*') %>%
  str_replace_all('  +', ' ') %>%
  str_remove('\\s+$') %>%
  cat()
```

## Analysis goals

```{r get_analysis_goals, eval=class(proposal_docx)=='docx'}
proposal_docx %>%
  safely_docx_extract_tbl(tbl_number=4, header=FALSE, preserve=TRUE) %>% pluck('result') %>%
  unlist() %>%
  safely_pluck(15) %>%
  str_remove('Please provide an outline of the goals of the analysis:\\s*') %>%
  str_replace_all('  +', ' ') %>%
  str_remove('\\s+$') %>%
  cat()
```

## Analysis details

```{r get_analysis_details, eval=class(proposal_docx)=='docx'}
proposal_docx %>%
  safely_docx_extract_tbl(tbl_number=4, header=FALSE, preserve=TRUE) %>% pluck('result') %>%
  unlist() %>%
  safely_pluck(18) %>%
  str_remove('Please provide details of the data analysis required.\\s*') %>%
  str_replace_all('  +', ' ') %>%
  str_remove('\\s+$') %>%
  cat()
```

```{r add_project_proposal_link, echo=FALSE}
cat('{{< callout note >}}\n')
system.file('docs/proposal.docx', package='datarepository') %>%
  when(.!=''~sprintf(fmt='The above text was auto-generated from the submitted [project proposal](%s). 🤖\n', .),
       TRUE~'The project proposal could not be read from the data-repository. Expected to find a proposal.docx file\n') %>%
  cat()
cat('{{< /callout >}}\n')
```
