<!-- show callouts for inputs/outputs summaries in columns if required -->

```{r get-inputs-outputs-summary}
#| cache: false
#| echo: false

rmarkdown::metadata |>
	purrr::pluck('report') |>
	purrr::keep_at(c('inputs summary', 'outputs summary')) -> io_summaries
```

:::: {layout-ncol=`r length(io_summaries)`}

```{r show-inputs-outputs-inputs}
#| cache: false
#| echo: false
#| eval: !expr io_summaries |> purrr::pluck('inputs summary') |> is.null() |> magrittr::not()
#| results: asis

# example front matter:
#
# ---
# report:
#   inputs summary:
#     - very short description
#     - which can be nested:
#       - like this
# ---

io_summaries |>
	purrr::pluck('inputs summary') |>
	yaml::as.yaml() |>
	(\(x) paste0('- ', x))() |>
	stringr::str_replace('^- - ', '- ') |>
	append(c('::: {.callout-tip icon=false}',
	         '## {{< fa sign-in >}} Inputs &nbsp;'), after=0) |>
	append(':::') |>
	cat(sep='\n')
```

```{r show-inputs-outputs-outputs}
#| cache: false
#| echo: false
#| eval: !expr io_summaries |> purrr::pluck('outputs summary') |> is.null() |> magrittr::not()
#| results: asis

# example front matter:
#
# ---
# report:
#   outputs summary:
#     - very short description
#     - which can be nested:
#       - like this
# ---

io_summaries |>
	purrr::pluck('outputs summary') |>
	yaml::as.yaml() |>
	(\(x) paste0('- ', x))() |>
	stringr::str_replace('^- - ', '- ') |>
	append(c('::: {.callout-tip icon=false}',
	         '## {{< fa sign-out >}} Outputs &nbsp;'), after=0) |>
	append(':::') |>
	cat(sep='\n')
```

::::

```{r tidy-up}
#| cache: false
#| echo: false

remove(io_summaries)
```